version: "3.9"
networks:
  localcdn-net:
    driver: bridge

services:
  # —————————————————————————————
  # 1) Static origin for HTML/assets
  origin:
    build:
      context: ./origin
    container_name: origin
    networks:
      - localcdn-net
    ports:
      - "8080:80"

  # —————————————————————————————
  # 2) Two “edge” cache nodes
  edge1:
    build: { context: ./edge }
    container_name: edge-us
    networks: [localcdn-net]
    ports: ["8081:80"]

  edge2:
    build: { context: ./edge }
    container_name: edge-eu
    networks: [localcdn-net]
    ports: ["8082:80"]

  # —————————————————————————————
  # 3) Nginx load balancer in front of your edges
  loadbalancer:
    build: { context: ./loadbalancer }
    container_name: lb
    networks: [localcdn-net]
    ports: ["8090:80"]
    depends_on:
      - edge1
      - edge2

  # —————————————————————————————
  # 4) MySQL database for your API
  db:
    image: mysql:8.0
    container_name: scorecard-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: scorecardnotes
    volumes:
      - ./api/prisma/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    networks: [localcdn-net]
    ports: ["3307:3306"]

  # —————————————————————————————
  # 5) Redis for caching
  redis:
    image: redis:6.2-alpine
    container_name: scorecard-redis
    restart: always
    networks: [localcdn-net]
    ports: ["6379:6379"]

  # —————————————————————————————
  # 6) Two identical API instances
  api1:
    build: { context: ./api }
    container_name: scorecard-api-1
    restart: always
    environment:
      DATABASE_URL: mysql://root:example@db:3306/scorecardnotes
      REDIS_URL: redis://redis:6379
    networks: [localcdn-net]
    expose:
      - "4000"
    depends_on:
      - db
      - redis

  api2:
    build: { context: ./api }
    container_name: scorecard-api-2
    restart: always
    environment:
      DATABASE_URL: mysql://root:example@db:3306/scorecardnotes
      REDIS_URL: redis://redis:6379
    networks: [localcdn-net]
    expose:
      - "4000"
    depends_on:
      - db
      - redis
